### ISSUE TITLE
Fetcher stops if insights service is temporarily unreachable

### ISSUE THREAD

**Issue by ivandov** [ivandov/insights-for-twitter-fetcher#1]
Found QUERY set in .env
Query: (IBM lang:en) AND posted:2017-02-26T17:07:10Z
undefined:1
404 Not Found: Requested route ('cdeservice.mybluemix.net') does not exist.
    ^
```
SyntaxError: Unexpected token N in JSON at position 4
    at Object.parse (native)
    at IncomingMessage.<anonymous> (/usr/src/app/helpers/twitter-fetcher.js:55:40)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by ivandov** [comment]
This also causes the cache to empty the "lastUpdate" value and subsequent restarts of the app fail.
